### ISSUE TITLE
Updating the config file

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#2903]
When there is a config file, and the user runs a command like `git town config push-hook yes`, it should update the config file instead of storing this setting in Git metadata. Options for updating the config file:

### De-serialize the existing config data structure to TOML.

```
++ easy to build
++ reliable
-- removes all comments from the file
```

### Search-and-replace the setting in the textual config file content.

```
++ minimal changes
++ comments get preserved
-- complicated to build, lots of edge cases
-- could fail to update a valid config file if it is formatted funny
-- could leave the configuration file in an invalid state
```

#### Variations that we have to deal with:

Nested vs dotted keys:

```toml
[branches]
perennials = ["one", "two"]

# vs

branches.perennials = ["one", "two"]
```

```toml
[code-hosting]
platform = "github"

# vs

code-hosting.platform = "github"
```

Single vs multi-line table:

```toml
[branches]
perennials = [
  "one", "two",
]

# vs

[branches]
perennials = [
  "one",
  "two",
]

# vs

branches.perennials = [
  "one",
  "two",
]
```

#### Don't update the config file, tell the user to do it manually.

```
++ easy to implement
-- poor UX
-- this option is redundant with the user not asking Git Town to update the file and instead doing it manually
```
