### ISSUE TITLE
option to auto-compress on sync

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#3320]
_Extracted from @tranhl in https://github.com/git-town/git-town/issues/2086#issuecomment-2051230333_
            
> Would it be possible to have an option to auto-compress commits when syncing stacks? That would help nicely with #3236 and the new rebase sync strategy behaviours introduced in v13!

**Comment by kevgo** [comment]
Possible names for the config option: 
- `auto-compress`
- `compress-on-sync`
- `sync-compress`

How this would look in the Git configuration:

```
git-town.auto-compress=true
git-town.compress-on-sync=true
git-town.sync-compress=true
```

In the config file

```toml
compress-on-sync = true
push-hook = true
push-new-branches = true
ship-delete-tracking-branch = false
sync-compress = true
sync-tags = false
sync-upstream = true
```
