### ISSUE TITLE
Better config file structure

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#3866]
### the problem

Our current config file is historically grown and now a bit of a mess. Options are scattered all over the place, making it hard for users to understand what's going on without reading a ton of comments.

```toml
push-hook = true
push-new-branches = false
ship-delete-tracking-branch = true
sync-upstream = true
ship-strategy = "squash-merge"
sync-tags = false

[branches]
main = "main"
perennials = ["public"]
perennial-regex = "^staging/"

[hosting]
platform = "github"
origin-hostname = "git.acme.com"

[sync-strategy]
feature-branches = "merge"
perennial-branches = "rebase"
```

### proposed solution

Let's group related options into sections that reflect the different phases of the development lifecycle.

```toml
# general setup
[branches]
main = "main"
default = "observed"
perennials = ["public"]
perennial-regex = "^staging/"

[hosting]
platform = "github"
origin-hostname = "git.acme.com"

# settings for creating branches
[create]
push-new-branches = false

# settings for syncing branches
[sync]
feature-strategy = "merge"
perennial-strategy = "rebase"
push-hook = true
upstream = true

# settings for proposing branches
[propose]

# settings for shipping branches
[ship]
delete-tracking-branch = true
strategy = "api"

# settings for the upcoming "deliver" feature
[deliver]
branch = "public"
strategy = "must-fast-forward"
```

### benefits 

This way, users can easily see which settings affect which part of their workflow. It also gives them a high-level overview of the development lifecycle.

### possible downsides

If a setting ends up being used in multiple phases, we'll have to move it around in the config file. We want to avoid changing the config structure too often.

### migrating to the new config file format

- Git Town should be able to read both the old and new config file structures.
- When it detects the old structure, it should suggest that the user upgrade by running `git town config upgrade`.
- The `git town config upgrade` command translates the old config file into the new structure.
